/**
 * Copies the Linear settings form into the settings extension.
 *
 * WHY A COPY, WHICH IS THE THING THIS PROJECT SWORE OFF
 * -----------------------------------------------------
 * HubSpot bundles each extension directory in isolation. The upload copies one
 * directory to a temp root and resolves from there, so an import that leaves it
 * cannot resolve:
 *
 *   Could not resolve "../pages/LinearSettingsForm.tsx"
 *     from "../../tmp/app/settings/SettingsPage.tsx"
 *
 * That is why no extension in this repo has ever imported across directories.
 * Sharing by import is not available, so the file has to exist in both places.
 *
 * What made the 2026-09-29 duplication harmful was not the copying — it was
 * that both copies were editable and nothing noticed when they diverged. Three
 * changes landed in the one nobody could see. So:
 *
 *   - pages/LinearSettingsForm.tsx is the ONLY file anyone edits
 *   - settings/LinearSettingsForm.tsx is generated, says so in its first line,
 *     and is regenerated by this script
 *   - settings-form-in-sync.test.ts fails the build if they differ
 *
 * A copy that cannot silently drift is a different thing from two
 * implementations.
 *
 * Usage:
 *   npm run sync:settings-form          regenerate
 *   npm run sync:settings-form -- --check   fail if stale, for CI
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(__dirname, '..', 'app');
export const SOURCE = join(ROOT, 'pages', 'LinearSettingsForm.tsx');
export const TARGET = join(ROOT, 'settings', 'LinearSettingsForm.tsx');

export const GENERATED_HEADER = `// GENERATED FILE — DO NOT EDIT.
//
// Source of truth: src/app/pages/LinearSettingsForm.tsx
// Regenerate with: npm run sync:settings-form
//
// This exists because HubSpot bundles each extension directory in isolation,
// so the settings extension cannot import across into pages/. Edits made here
// are overwritten, and settings-form-in-sync.test.ts fails while the two files
// differ.
`;

/** What the generated file should contain, given the source. */
export function render(source: string): string {
  return `${GENERATED_HEADER}\n${source}`;
}

function main() {
  const source = readFileSync(SOURCE, 'utf8');
  const expected = render(source);
  const check = process.argv.includes('--check');

  let current = '';
  try { current = readFileSync(TARGET, 'utf8'); } catch { /* not generated yet */ }

  if (current === expected) {
    console.log('settings form is in sync');
    return;
  }
  if (check) {
    console.error('settings form is STALE — run: npm run sync:settings-form');
    process.exit(1);
  }
  writeFileSync(TARGET, expected);
  console.log(`wrote ${TARGET}`);
}

// Runs as a script, stays quiet when the test imports it for its paths.
if (process.argv[1]?.includes('sync-settings-form')) main();
